name: Daily POST Request

on:
  schedule:
    - cron: '25 4 * * 1-5' # 上海时区中午12:25，对应的UTC时间是前一天晚上20:25 (UTC+8)

jobs:
  post_request:
    runs-on: ubuntu-latest
    env:
      TIME_ZONE: Asia/Shanghai
      URL: https://carbon-account-server.carbonstop.net/task/completeTimeTripTask
      BEARER_TOKEN: eyJhbGciOiJIUzUxMiJ9.eyJjb21wYW55X2lkIjoxMDAwMDAwNzQyNzkwMTYyLCJ1c2VyX2lkIjozOTQzNjEsInVzZXJfa2V5IjoiMTAwMDAwMDc0Mjc5MDE2MjpvRmNBZDVCcjIwQk5GUFlyUmV5ZHI3cUZPTlRNOjE5NzE5MzVhLTEyNzUtNDU1My1hMWE2LTY1ZjA4YmE2ZWE1MyIsInVzZXJuYW1lIjoib0ZiQWQ1QnoyMEJORlBZclJleWRyN3FGT05UTSJ9._r_kzgwCvFCaqZgzhT46LAlmvTC71yyJP43yNYkjmoSrJ-N2EzymlSlu7V00BvRlEtNFBwWH3ToWOjgTTo39TA
      REQUEST_BODY: '{"value":"1","sceneCode":"MRCJ0021","signMessage":"3df1c430e4c80f62f9faa809bf380c06"}'

    steps:
      - name: Set up timezone
        uses: zcong1993/set-timezone-action@v1.1.1
        with:
          timezone_id: ${{ env.TIME_ZONE }}

      - name: Send POST request
        id: send_post
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $BEARER_TOKEN" \
            -d "$REQUEST_BODY" \
            $URL \
            -o response.json
          
          echo "Response:"
          cat response.json

      - name: Log response status
        run: |
          RESPONSE_STATUS=$(jq -r '.status' response.json)
          echo "Response Status: $RESPONSE_STATUS"
