name: Daily POST Request 1F

on:
  schedule:
    - cron: '10 4 * * 1-5' # 上海时区中午12:25，对应的UTC时间是前一天晚上20:25 (UTC+8)
    - cron: '35 4 * * 1-5' # 上海时区中午12:35，对应的UTC时间是前一天晚上20:25 (UTC+8)
    - cron: '45 4 * * 1-5' # 上海时区中午12:45，对应的UTC时间是前一天晚上20:25 (UTC+8)
  workflow_dispatch:

jobs:
  read-config-file:
    runs-on: ubuntu-latest
    env:
      #Request 1F
      URL: https://carbon-account-server.carbonstop.net/task/completeTimeTripTask
      REQUEST_BODY: '{"value":"1","sceneCode":"MRCJ0021","signMessage":"3df1c430e4c80f62f9faa809bf380c06"}'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Request
        run: |
          #!/bin/bash
          # Read the configuration file and process each line
          while IFS='=' read -r name token; do
            echo "Key: $name, Value: $token"
            echo "正在执行的账户: $name"
            curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization:$token" \
            -d "$REQUEST_BODY" \
            $URL \
            -o response.json
          
            echo "Response:"
            cat response.json  
          done < config.properties
      - name: Log response status
        run: |
          RESPONSE_STATUS=$(jq -r '.status' response.json)
          echo -e "Response Status: $RESPONSE_STATUS \n"
