name: Daily POST Request Box

on:
  #schedule:
   # - cron: '26 4 * * 1-5' # 上海时区中午12:26，
  workflow_dispatch:

jobs:
  read-config-file:
    runs-on: ubuntu-latest
    env:
      #Request Box
      URL: https://carbon-account-server.carbonstop.net/task/complete
      REQUEST_BODY: '{"sceneCode":"MRCJ1889","value":1,"signMessage":"38173cda070782f86b6c2b3e92192156"}'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Request Box
        run: |
          #!/bin/bash
          # Read the configuration file and process each line
          while IFS='=' read -r name token; do
            echo "Key: $name, Value: $token"
            echo "正在执行的账户: $name"
            curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization:$token" \
            -d "$REQUEST_BODY" \
            $URL \
            -o response.json
          
            echo "Response:"
            cat response.json  
          done < config.properties
          sleep 10
          while IFS='=' read -r name token; do
            echo "Key: $name, Value: $token"
            echo "正在执行的账户: $name"
            curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization:$token" \
            -d "$REQUEST_BODY" \
            $URL \
            -o response.json
          
            echo "Response:"
            cat response.json  
          done < config.properties
          sleep 10
          while IFS='=' read -r name token; do
            echo "Key: $name, Value: $token"
            echo "正在执行的账户: $name"
            curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization:$token" \
            -d "$REQUEST_BODY" \
            $URL \
            -o response.json
          
            echo "Response:"
            cat response.json  
          done < config.properties
      - name: Log response status
        run: |
          RESPONSE_STATUS=$(jq -r '.status' response.json)
          echo -e "Response Status: $RESPONSE_STATUS \n"
