name: Daily POST Request 24F to 1F

on:
  schedule:
    - cron: '10 4 * * 1-5' # 上海时区中午12:25，对应的UTC时间是前一天晚上20:34 (UTC+8)
  workflow_dispatch:

jobs:
  read-config-file:
    runs-on: ubuntu-latest
    env:
      URL: https://carbon-account-server.carbonstop.net/task/completeTimeTripTask
      REQUEST_BODY: '{"sceneCode":"MRCJ0021","value":"24","signMessage":"fcff47b42c5a6782387ea2cf3d4e33d6"}'
      REQUEST_BODY_1: '{"value":"1","sceneCode":"MRCJ0021","signMessage":"3df1c430e4c80f62f9faa809bf380c06"}'
      REQUEST_BODY_24: '{"sceneCode":"MRCJ0021","value":"24","signMessage":"fcff47b42c5a6782387ea2cf3d4e33d6"}'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Request
        run: |
          #!/bin/bash
          # Read the configuration file and process each line
          # 扫第一次
          while IFS='=' read -r name token; do
            echo "Key: $name, Value: $token"
            echo "正在执行的账户: $name"
            curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization:$token" \
            -d "$REQUEST_BODY_1" \
            $URL \
            -o response.json
          
            echo "Response:"
            cat response.json  
          done < config.properties
          #等5分钟
          sleep 300
          while IFS='=' read -r name token; do
            echo "Key: $name, Value: $token"
            echo "正在执行的账户: $name"
            curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization:$token" \
            -d "$REQUEST_BODY_24" \
            $URL \
            -o response.json
          
            echo "Response:"
            cat response.json  
          done < config.properties
          #等20秒
          sleep 20
          # 扫第二次
          while IFS='=' read -r name token; do
            echo "Key: $name, Value: $token"
            echo "正在执行的账户: $name"
            curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization:$token" \
            -d "$REQUEST_BODY_1" \
            $URL \
            -o response.json
          
            echo "Response:"
            cat response.json  
          done < config.properties
          #等5分钟
          sleep 300
          while IFS='=' read -r name token; do
            echo "Key: $name, Value: $token"
            echo "正在执行的账户: $name"
            curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization:$token" \
            -d "$REQUEST_BODY_24" \
            $URL \
            -o response.json
          
            echo "Response:"
            cat response.json  
          done < config.properties
          #等20秒
          sleep 20
          # 扫第三次
          while IFS='=' read -r name token; do
            echo "Key: $name, Value: $token"
            echo "正在执行的账户: $name"
            curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization:$token" \
            -d "$REQUEST_BODY_1" \
            $URL \
            -o response.json
          
            echo "Response:"
            cat response.json  
          done < config.properties
          #等5分钟
          sleep 300
          while IFS='=' read -r name token; do
            echo "Key: $name, Value: $token"
            echo "正在执行的账户: $name"
            curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization:$token" \
            -d "$REQUEST_BODY_24" \
            $URL \
            -o response.json
          
            echo "Response:"
            cat response.json  
          done < config.properties

      - name: Log response status
        run: |
          RESPONSE_STATUS=$(jq -r '.status' response.json)
          echo -e "Response Status: $RESPONSE_STATUS \n"
