name: Daily POST Request Question

on:
  #schedule:
   # - cron: '16 4 * * *' # 上海时区中午12:16，
  workflow_dispatch:

jobs:
  read-config-file:
    runs-on: ubuntu-latest
    env:
      #Request Question
      URL: https://carbon-account-server.carbonstop.net/question/submit
      REQUEST_BODY: '[{"answerA":"合理保证就是保证数据是绝对准确的  ","correctAnswer":"A","updateTime":"2022-07-15 18:59:16","answerB":"合理保证说明数据是相对准确和可以信赖的","questionTitle":"关于保证等级说法不正确的是","answerC":"任何组织的温室气体核查都可要求作有限保证的评审","answerNum":0,"questionLabels":["001"],"delFlag":0,"answerD":"有限保证对数据的完整性做有限度的评审  ","id":351,"delFlag_name":"正常","questionType_name":"单选","createBy":0,"questionType":1,"answerE":null,"updateBy":0,"questionType_name_format":"单选","answerF":null,"createTime":"2022-07-15 18:54:26","answerG":null},{"answerA":"国际排放因子","correctAnswer":"B","updateTime":"2022-07-15 19:04:26","answerB":"相同工艺\/设备的经验系数获得的排放因子","questionTitle":"在核查过程中常用排放因子法来计算温室气体排放量，以下4类排放因子中，数据质量较高的是（ ）","answerC":"区域排放因子","answerNum":0,"questionLabels":["001"],"delFlag":0,"answerD":"设备制造商提供的系数获得的排放因子","id":316,"delFlag_name":"正常","questionType_name":"单选","createBy":0,"questionType":1,"answerE":null,"updateBy":0,"questionType_name_format":"单选","answerF":null,"createTime":"2022-07-15 18:54:26","answerG":null},{"answerA":"家用冰箱运行3天","correctAnswer":"C","updateTime":"2022-07-15 18:54:26","answerB":"普通电视机持续开1天","questionTitle":"1度电相当于(   ):","answerC":"25瓦的灯泡能连续点亮40小时","answerNum":0,"questionLabels":["001"],"delFlag":0,"answerD":"将20公斤的水烧开","id":406,"delFlag_name":"正常","questionType_name":"单选","createBy":0,"questionType":1,"answerE":null,"updateBy":0,"questionType_name_format":"单选","answerF":null,"createTime":"2022-07-15 18:54:26","answerG":null},{"answerA":"资源","correctAnswer":"A","updateTime":"2022-07-15 18:54:26","answerB":"污染","questionTitle":"通常认为垃圾是放错了地方的__________。","answerC":"废物","answerNum":0,"questionLabels":["001"],"delFlag":0,"answerD":null,"id":107,"delFlag_name":"正常","questionType_name":"单选","createBy":0,"questionType":1,"answerE":null,"updateBy":0,"questionType_name_format":"单选","answerF":null,"createTime":"2022-07-15 18:54:26","answerG":null},{"answerA":"解决好经济增长——能源消费——GHG减排的三角关系","correctAnswer":"A,B,C","updateTime":"2022-07-15 19:02:41","answerB":"调整能源消费结构的同时保障能源供应","questionTitle":"实现”30·60”目标需要直面的三大难题","answerC":"环境治理与减排不能给大众带来沉重的经济负担","answerNum":0,"questionLabels":["001"],"delFlag":0,"answerD":null,"id":550,"delFlag_name":"正常","questionType_name":"多选","createBy":0,"questionType":2,"answerE":null,"updateBy":0,"questionType_name_format":"多选","answerF":null,"createTime":"2022-07-15 18:54:26","answerG":null}]'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Request
        run: |
          #!/bin/bash
          # Read the configuration file and process each line
          while IFS='=' read -r name token; do
            echo "Key: $name, Value: $token"
            echo "正在执行的账户: $name"
            curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization:$token" \
            -d "$REQUEST_BODY" \
            $URL \
            -o response.json
          
            echo "Response:"
            cat response.json  
          done < config.properties
          sleep 10
          while IFS='=' read -r name token; do
            echo "Key: $name, Value: $token"
            echo "正在执行的账户: $name"
            curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization:$token" \
            -d "$REQUEST_BODY" \
            $URL \
            -o response.json
          
            echo "Response:"
            cat response.json  
          done < config.properties
      - name: Log response status
        run: |
          RESPONSE_STATUS=$(jq -r '.status' response.json)
          echo -e "Response Status: $RESPONSE_STATUS \n"
