name: Daily POST Request Box

on:
  schedule:
    - cron: '26 4 * * 1-5' # 上海时区中午12:26，
    - cron: '27 4 * * 1-5' # 上海时区中午12:27，
    - cron: '28 4 * * 1-5' # 上海时区中午12:28，
  workflow_dispatch:

jobs:
  post_request:
    runs-on: ubuntu-latest
    env:
      URL: https://carbon-account-server.carbonstop.net/task/complete
      REQUEST_BODY: '{"sceneCode":"MRCJ1889","value":1,"signMessage":"38173cda070782f86b6c2b3e92192156"}'
      BEARER_TOKEN: 'eyJhbGciOiJIUzUxMiJ9.eyJjb21wYW55X2lkIjoxMDAwMDAwNzQyNzkwMTYyLCJ1c2VyX2lkIjozOTQzNjEsInVzZXJfa2V5IjoiMTAwMDAwMDc0Mjc5MDE2MjpvRmJBZDVCejIwQk5GUFlyUmV5ZHI3cUZPTlRNOjcyOWU2MmFhLTNkYzEtNGQ3ZS1iY2IwLTcxY2YyMTQyYmE2NiIsInVzZXJuYW1lIjoib0ZiQWQ1QnoyMEJORlBZclJleWRyN3FGT05UTSJ9.rgKPBYqNBGtJLSHJtkcr-7-MCOp1yHXirzuHBdNjKqMfJF5vOvKSHaWcRyXuY5kjnnzWAjp0uVQbbO5YWUSipA,eyJhbGciOiJIUzUxMiJ9.eyJjb21wYW55X2lkIjoxMDAwMDAwNzQyNzkwMTYyLCJ1c2VyX2lkIjozOTgyMjIsInVzZXJfa2V5IjoiMTAwMDAwMDc0Mjc5MDE2MjpvRmJBZDVBbG95SnJWTmZuYzBMNko5ODFIZ1Y0OjI3MTkzMjBmLTVkZjgtNDJlMC05NjVhLWE5NGU4YzdhM2M1ZiIsInVzZXJuYW1lIjoib0ZiQWQ1QWxveUpyVk5mbmMwTDZKOTgxSGdWNCJ9.NPTazHv347GBqTKFj7WX_vju46v85TXY5BIeG_XL5nehU0k0e659-ppcWufLzyDB-YFNvXoV_-C59P8b1Uo6Lg,eyJhbGciOiJIUzUxMiJ9.eyJjb21wYW55X2lkIjoxMDAwMDAwNzQyNzkwMTYyLCJ1c2VyX2lkIjozOTc2OTcsInVzZXJfa2V5IjoiMTAwMDAwMDc0Mjc5MDE2MjpvRmJBZDVPWHJ5bHVHSWRxVFhvT0FIaU84QTZ3OjIwOGZjNjQ0LTkxMmQtNDkzNi04ODg2LTQ0MzA4ZmE2MDY2MyIsInVzZXJuYW1lIjoib0ZiQWQ1T1hyeWx1R0lkcVRYb09BSGlPOEE2dyJ9.EGu9MVN25QvPBODTY-0qUnKxYmK1EA7hs5WyTAqhFMCLopShRTTxYWtbLpEcdw2sFGBv-t1NjwMthwS8A3KA4A,eyJhbGciOiJIUzUxMiJ9.eyJjb21wYW55X2lkIjoxMDAwMDAwNzQyNzkwMTYyLCJ1c2VyX2lkIjozOTQzNjAsInVzZXJfa2V5IjoiMTAwMDAwMDc0Mjc5MDE2MjpvRmJBZDVQWHJwMlFiMkRBMU5NSzdhUFhhcHZrOjcxZjQwNGJlLWU0ZTktNDc4My05NjI2LTBmNGFjNGE0NzI3YSIsInVzZXJuYW1lIjoib0ZiQWQ1UFhycDJRYjJEQTFOTUs3YVBYYXB2ayJ9.Wkjb4Wuxb4VEP-eS_SJcoEARWgvC20Phz2W1fDvh41neU06S_8ocVYY9HlVo24LlfdSd4vytuOByMz6AGWbrJQ'
      NAME: 'Will,TianCheng,LongAoTian,DanDan'

    steps:
      - name: Send POST request
        id: send_post
        run: |
          IFS=',' read -ra TOKENS <<< "$BEARER_TOKEN"
          IFS=',' read -ra NAMES <<< "$NAME"
          for i in "${!TOKENS[@]}"; do
              token="${TOKENS[$i]}"
              name="${NAMES[$i]}"
              echo "正在执行的账户: $name"
              curl -X POST \
                -H "Content-Type: application/json" \
                -H "Authorization:$token" \
                -d "$REQUEST_BODY" \
                $URL \
                -o response.json
              
                echo "Response:"
                cat response.json
              done
      - name: Log response status
        run: |
          RESPONSE_STATUS=$(jq -r '.status' response.json)
          echo "Response Status: $RESPONSE_STATUS"
