name: Example Workflow 2
on:
  push:
    branches:
      - main

jobs:
  read-config-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read configuration file
        run: |
          #!/bin/bash
          # Read the configuration file and process each line
          while IFS='=' read -r key value; do
            echo "Key: $key, Value: $value"
          done < config.properties
