name: meiyou_pee

on:
  repository_dispatch:
    types: [meiyou_pee-notification]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up timezone
      run: sudo timedatectl set-timezone Asia/Shanghai
    - name: Send meiyou_pee
      env:
        MEIYOU_KEY: ${{ secrets.MEIYOU_KEY }}  # 从 GitHub Secrets 获取你的 Bark Key
      run: |
        echo "Sending meiyou_pee Notification..."
        CURRENT_TIME=$(date +"%Y-%m-%d %H:%M:%S")
        echo $CURRENT_TIME
        curl -X POST "https://api-bbj.meiyou.com/v3/life/record" \
             -H "Content-Type: application/json" \
             -H "Authorization: $MEIYOU_KEY" \
             -d '{"record_category":41,"uni":"4_0","record_type":4,"baby_id":110281244,"record_detail":{"shit_shape":0,"urine_volume":0,"red_buttock":false,"shit_color":0},"start_at":"2025-01-04 17:51:00"}'


             
