name: Run All Scripts

on:
  workflow_dispatch:  # 允许手动触发此工作流

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Run Daily POST Request 24F to 1F
        uses: actions/github-script@v4
        with:
          script: |
            await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'Daily POST Request 24F to 1F.yml',
              ref: 'master'  // 根据你的实际分支名称替换
            });

      - name: Run Daily POST Request Question
        uses: actions/github-script@v4
        with:
          script: |
            await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'Daily POST Request Question.yml',
              ref: 'master'  
            });

      - name: Run Daily_POST_Request_Bike
        uses: actions/github-script@v4
        with:
          script: |
            await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'Daily_POST_Request_Bike.yml',
              ref: 'master'  
            });

      - name: Run Daily_POST_Request_Box
        uses: actions/github-script@v4
        with:
          script: |
            await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'Daily_POST_Request_Box.yml',
              ref: 'master'  
            });

      - name: Run Daily_POST_Request_SignIn
        uses: actions/github-script@v4
        with:
          script: |
            await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'Daily_POST_Request_SignIn.yml',
              ref: 'master'  
            });
