name: Shared Jobs

on:
  workflow_call:  # 使用workflow_call来定义一个可被其他Workflow调用的Job
    inputs:
      url:
        required: true
        type: string
      bearer_token:
        required: true
        type: string
      request_body:
        required: true
        type: string
    outputs:
      response_status:
        description: "The status of the response"
        value: ${{ jobs.post_request.outputs.response_status }}

jobs:
  post_request:
    runs-on: ubuntu-latest
    outputs:
      response_status: ${{ steps.log_response_status.outputs.response_status }}  # 定义输出

    steps:
      - name: Send POST request
        id: send_post
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization:eyJhbGciOiJIUzUxMiJ9.eyJjb21wYW55X2lkIjoxMDAwMDAwNzQyNzkwMTYyLCJ1c2VyX2lkIjozOTQzNjEsInVzZXJfa2V5IjoiMTAwMDAwMDc0Mjc5MDE2MjpvRmJBZDVCejIwQk5GUFlyUmV5ZHI3cUZPTlRNOjE5NzE5MzVhLTEyNzUtNDU1My1hMWE2LTY1ZjA4YmE2ZWE1MyIsInVzZXJuYW1lIjoib0ZiQWQ1QnoyMEJORlBZclJleWRyN3FGT05UTSJ9._r_kzgwCvFCaqZgzhT46LAlmvTC71yyJP43yNYkjmoSrJ-N2EzymlSlu7V00BvRlEtNFBwWH3ToWOjgTTo39TA" \
            -d "data:{"value":"1","sceneCode":"MRCJ0021","signMessage":"3df1c430e4c80f62f9faa809bf380c06"}" \
            https://carbon-account-server.carbonstop.net/task/completeTimeTripTask \
            -o response.json
          
          echo "Response:"
          cat response.json

