
name: TCPing Check

on:
  workflow_dispatch:


yaml
name: TCPing Check

on:
  workflow_dispatch:

jobs:
  tcping_check:
    runs-on: ubuntu-latest
    steps:
    - name: Make GET Request to TCPing API
      id: tcping_request
      run: |
        nslookup v2.api-m.com
